# Generated by Django 5.1 on 2024-08-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_drf', '0004_order_orderitem_order_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
    ]
