# Generated by Django 5.1 on 2024-08-29 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0002_address_event_alter_product_category_comment_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
