# Generated by Django 5.1 on 2024-08-26 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_requestfriends_unique_together_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
